### Importing Libraries and Dependencies

In [1]:
import torch    

In [2]:
# Membuat variabel dengan mengaktifkan 'requres_grad'
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
z = z.mean()
print(z)

tensor([-1.2957, -1.1464,  0.5050], requires_grad=True)
tensor([0.7043, 0.8536, 2.5050], grad_fn=<AddBackward0>)
tensor(7.4999, grad_fn=<MeanBackward0>)


#### Menghitung gradien

In [3]:
# dz/dx
z.backward()
print(x.grad)

tensor([1.4086, 1.7073, 5.0101])


In [5]:
x = torch.randn(3, requires_grad = True)
y = x * 2 
z = y * y * 3

v = torch.tensor([0.1, 1.0, 0.0001], dtype= torch.float)
z.backward(v)
print(x.grad)

tensor([ 1.1926e+00, -4.6546e+01,  3.2667e-03])


#### Menghentikan Tracking Gradien

In [6]:
x = torch.randn(3, requires_grad=True)
y = torch.randn(3, requires_grad=True)
z = torch.randn(3, requires_grad=True)
print(x)
print(y)
print(z)

tensor([-0.2968,  2.0451,  0.6217], requires_grad=True)
tensor([-0.5329,  1.9461, -0.2756], requires_grad=True)
tensor([ 0.6535,  2.5202, -0.3646], requires_grad=True)


In [7]:
x.requires_grad_(False)
print(x)

tensor([-0.2968,  2.0451,  0.6217])


In [8]:
y = y.detach()
print(y)

tensor([-0.5329,  1.9461, -0.2756])


In [9]:
with torch.no_grad():
    z = x + y
    print(z)

tensor([-0.8297,  3.9912,  0.3462])


In [10]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [11]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [13]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
# gunakan optimizer untuk mengoptimalkan nilai weights
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor