### Basic Operations in Pytorch Tensor

#### Mengimport library dan dependencies

In [2]:
import torch

#### Membuat variabel baru bertipe tensor

In [3]:
# Empty variabel dengan ukuran 2,4
emptyvar = torch.empty(2, 4)
print(emptyvar)

tensor([[3.4004e-06, 2.0972e-07, 8.1929e-10, 3.3234e-09],
        [4.2698e-08, 2.0803e+23, 6.9062e-07, 2.1259e+20]])


In [4]:
# Variabel random dengan ukuran 2, 3, 4
randomvar = torch.rand(2, 3, 4)
print(randomvar)

tensor([[[0.8136, 0.5679, 0.1600, 0.7514],
         [0.3811, 0.2534, 0.0329, 0.9424],
         [0.8321, 0.7647, 0.8617, 0.5069]],

        [[0.8234, 0.4432, 0.1782, 0.3337],
         [0.2203, 0.2519, 0.1866, 0.5912],
         [0.6606, 0.4317, 0.9455, 0.8771]]])


In [5]:
# Variabel Tensor dengan nilai 1 ukuran 2, 3, 4
onesvar = torch.ones(2, 3, 4)
print(onesvar)

# Variabel Tensor dengan nilai 0 ukuran 2, 3, 4
zerosvar = torch.zeros(2, 3, 4)
print(zerosvar)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
# Membuat variabel tensor yang berurut sejumlah n dari x hingga y
range = torch.arange(12, dtype=torch.float32)
range2 = torch.arange(0, 12, 2, dtype=torch.float32)

print(range)
print(range2)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([ 0.,  2.,  4.,  6.,  8., 10.])


#### Membuat Variabel tensor dengan tipe data spesifik

In [7]:
# Integer
intvar = torch.ones(2, 2, dtype=torch.int)
# float
floatvar = torch.rand(2, 2, dtype=torch.float32)

print(intvar, floatvar)
print(intvar.dtype, floatvar.dtype)
print(intvar.size(),floatvar.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32) tensor([[0.4161, 0.2164],
        [0.0767, 0.4982]])
torch.int32 torch.float32
torch.Size([2, 2]) torch.Size([2, 2])


#### Operasi Aritmatika dasar pada Tensor

In [8]:
# mengisi tensor dengan nilai 
var_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
var_b = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Operasi artimatika
var_c = var_a + var_b
print(var_c)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


#### Cara Lain menjumlah 

In [9]:
var_c = torch.add(var_a, var_b)
print(var_c)

# cara lain pada variabel yang sama (in-place operation)
var_a.add_(var_b)
print(var_a)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


#### Operasi artimatika Lainnya

In [10]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# dot product
z_kali = x * y
z_kali_2 = torch.mul(x, y)

z_frac = x / y
z_frac_2 = torch.div(x, y)

z_kurang = x - y
z_kurang_2 = torch.sub(x, y)

z_pangkat = x**y
z_pangkat_2 = torch.pow(x, y)

print(z_kali, z_kali_2, z_frac, z_frac_2, z_kurang, z_kurang_2, z_pangkat, z_pangkat_2)

tensor([[0.2229, 0.3539],
        [0.2027, 0.5441]]) tensor([[0.2229, 0.3539],
        [0.2027, 0.5441]]) tensor([[1.3828, 1.2127],
        [3.1692, 0.6696]]) tensor([[1.3828, 1.2127],
        [3.1692, 0.6696]]) tensor([[ 0.1537,  0.1149],
        [ 0.5486, -0.2979]]) tensor([[ 0.1537,  0.1149],
        [ 0.5486, -0.2979]]) tensor([[0.7896, 0.7957],
        [0.9456, 0.6344]]) tensor([[0.7896, 0.7957],
        [0.9456, 0.6344]])


#### Manipulasi Matriks

In [11]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # mencetak hanya kolom pertama
print(x[0, :])  # mencetak hanya baris pertama
print(x[1, 1])  # mencetak nilai pada baris ke-1 dan kolom ke-1
print(x[1, 1].item())  # mencetak hanya nilai (tanpa identitas jenis tensor)

tensor([[0.9149, 0.9622, 0.5024],
        [0.9539, 0.7438, 0.8093],
        [0.6001, 0.2999, 0.0226],
        [0.6113, 0.4384, 0.2521],
        [0.0305, 0.8634, 0.9894]])
tensor([0.9149, 0.9539, 0.6001, 0.6113, 0.0305])
tensor([0.9149, 0.9622, 0.5024])
tensor(0.7438)
0.7437773942947388


### Reshaping Matriks
Mengubah matriks 2 dimensi menjadi array 1 dimensi


In [12]:
x = torch.rand(4, 4)
print(x)
print(x.shape)
y = x.view(16)
print(y)
print(y.shape)

tensor([[0.8289, 0.1950, 0.3957, 0.1228],
        [0.0808, 0.6138, 0.6769, 0.9860],
        [0.8775, 0.8455, 0.8615, 0.9559],
        [0.0615, 0.4320, 0.2414, 0.8800]])
torch.Size([4, 4])
tensor([0.8289, 0.1950, 0.3957, 0.1228, 0.0808, 0.6138, 0.6769, 0.9860, 0.8775,
        0.8455, 0.8615, 0.9559, 0.0615, 0.4320, 0.2414, 0.8800])
torch.Size([16])


In [13]:
y = x.view(-1, 8) 
print(y)
print(y.shape)
# --- nilai -1 pada fungsi `view`` menandakan dimensi pertama otomatis mengikuti bentuk tensor awal, 
# dalam hal ini karena data ada 4*4 = 16 elemen, maka dimensi pertama menjadi 16/8 = 2

tensor([[0.8289, 0.1950, 0.3957, 0.1228, 0.0808, 0.6138, 0.6769, 0.9860],
        [0.8775, 0.8455, 0.8615, 0.9559, 0.0615, 0.4320, 0.2414, 0.8800]])
torch.Size([2, 8])


In [14]:
x = torch.rand(2, 4, 5)
print(x)

x_new = x.view(8, -1)
print(x_new)

tensor([[[0.9778, 0.2102, 0.9020, 0.7063, 0.3360],
         [0.7579, 0.2619, 0.8039, 0.5702, 0.6716],
         [0.1489, 0.2137, 0.6321, 0.9269, 0.8876],
         [0.2440, 0.0391, 0.9847, 0.9533, 0.3723]],

        [[0.5301, 0.5880, 0.3839, 0.7577, 0.0830],
         [0.3975, 0.5054, 0.7667, 0.3918, 0.0139],
         [0.5252, 0.3967, 0.3626, 0.9380, 0.1299],
         [0.4637, 0.6913, 0.5694, 0.5506, 0.9478]]])
tensor([[0.9778, 0.2102, 0.9020, 0.7063, 0.3360],
        [0.7579, 0.2619, 0.8039, 0.5702, 0.6716],
        [0.1489, 0.2137, 0.6321, 0.9269, 0.8876],
        [0.2440, 0.0391, 0.9847, 0.9533, 0.3723],
        [0.5301, 0.5880, 0.3839, 0.7577, 0.0830],
        [0.3975, 0.5054, 0.7667, 0.3918, 0.0139],
        [0.5252, 0.3967, 0.3626, 0.9380, 0.1299],
        [0.4637, 0.6913, 0.5694, 0.5506, 0.9478]])


In [15]:
x = torch.arange(6, 100, 3, dtype=torch.float32)
print(x)
print(x.size())

x_new = x.reshape(4,8)
print(x_new)

# perlu diingat bahwa target reshape harus sama dengan jumlah elemen yang ada pada tensor awal

tensor([ 6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39., 42., 45.,
        48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78., 81., 84., 87.,
        90., 93., 96., 99.])
torch.Size([32])
tensor([[ 6.,  9., 12., 15., 18., 21., 24., 27.],
        [30., 33., 36., 39., 42., 45., 48., 51.],
        [54., 57., 60., 63., 66., 69., 72., 75.],
        [78., 81., 84., 87., 90., 93., 96., 99.]])


### Konversi dari Numpy ke Tensor

In [16]:
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a = a + 1
print(a)
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


#### Operasi dengan GPU

In [19]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    # Mengatur nama device sebagai variabel
    device = torch.device("cuda")
    # Membuat variabel tensor yang menggunakan device
    x = torch.ones(5, device=device)

    # Memindahkan variable yang sudah dibuat sebelumnya ke device
    y = torch.ones(5)
    y = y.to(device)

    # Memindahkan kembali ke CPU
    x = x.to("cpu")

False


In [20]:
x = torch.ones(2, 2, requires_grad=True) # memungkinkan pytorch untuk menghitung gradient secara otomatis
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
